 const carspec=[
    {
        name:"acura-ilx",
        model:2021,
        price:50000,
        slug:"acura-ilx"
    },
    {
        name:"audi-rs5",
        model:2021,
        price:40000,
        slug:"audi-rs5"
    },
    {
        name:"audi-s4",
        model:2021,
        price:23000,
        slug:"audi-s4"
    },
    {
        name:"bmw-m2",
        model:2021,
        price:30000,
        slug:"bmw-m2"
    },
    {
        name:"bmw-x6",
        model:2021,
        price:50000,
        slug:"bmw-x6"
    },
    {
        name:"chrysler-300",
        model:2021,
        price:50000,
        slug:"chrysler-300"
    },
    {
        name:"dodge-charger",
        model:2021,
        price:50000,
        slug:"dodge-charger"
    },
    {
        name:"maserati-quattroporte",
        model:2021,
        price:100000,
        slug:"maserati-quattroporte"
    },
    {
        name:"polestar-2",
        model:2021,
        price:50000,
        slug:"polestar-2"
    },
    {
        name:"subaru-legacy",
        model:2021,
        price:50000,
        slug:"subaru-legacy"
    },
    {
        name:"toyota-avalon",
        model:2021,
        price:50000,
        slug:"toyota-avalon"
    },
    {
        name:"mercedes-benzaclass",
        model:2021,
        price:50300,
        slug:"mercedes-benzaclass"
    },
    {
        name:"toyota-camry",
        model:2021,
        price:54000,
        slug:"toyota-camry"
    },
    {
        name:"volkswagen-gti",
        model:2021,
        price:50000,
        slug:"volkswagen-gti"
    },
];
export default carspec